#!/usr/bin/env -S ruby -w
# frozen_string_literal: true

require 'stouch_remote'
require 'stouch_remote/gui'

logger = Logger.new(STDOUT)
logger.level = Logger::INFO

conn = STouchRemote::Connection.new('192.168.1.70', 8080, logger: logger)
ui = STouchRemote::Gui.new(conn, logger)
ui.run
